alert("Hey sunshine")
alert("I thought about this for a while, creating something you can comeback to when you feel down…that would put this writing a level above your book boyfriends right?🤣")
alert("I can do the “When nothing seems to go your way, Remember that you're not alone” but screw that let do something else")
alert("Every Friday I take the pleasure of finding a new way to compliment you. Telling you that you look nice is an understatement like Park said about your name sake in Rainbow Rowell’s novel")
alert("“Eleanor was right. She never looked nice. She looked like art, and art wasn't supposed to look nice; it was supposed to make you feel something.”")
alert("You invoke a special feeling of tenderness, something people never feel until they meet you ")
alert("You’re not beautiful for something as worldly or as temporary as your looks, you’re beautiful for your soul")
alert("I could tell you about all the boxes you check, I would use Fridays for those. And if you are ever in doubt, just look at a mirror.")
alert("Any “homeboy” that ends up with you should count himself lucky cause it takes more than a four-leaf clover or wishing on a star to get you…make sure you give him hell and I would probably make crass jokes🤣")
alert("Well byeeeeeeeeeeeee!!!!!!!!!!!")